excel:
  path: "C:/Users/andre/Downloads/clientes_prueba.xlsx"
  header_row: 1

columnas:
  tipo_transaccion: "TIPO TRANSACCION"
  cliente: "CLIENTE"
  placa: "PLACA"
  valor_actual: "VALOR ACTUAL"
  porcentaje_interes: "% INTERES"
  valor_interes_mensual: "VALOR INTERES MENSUAL"
  vencimiento_interes: "VENCIMIENTO DEL INTERES"
  dias_corridos: "DIAS CORRIDOS"
  valor_interes_vencido: "VALOR TOTAL INTERES VENCIDO A HOY"
  saldo_actual: "SALDO ACTUAL"
  telefono: "TELEFONO"

whatsapp:
  token: "EAANfB26PNGQBRTxQYMslKHZAUzwZAxZAYbdMcpiY7ODWaLscMHWkxTXZCPVYSPuYR0RcZBVXv22t1CSJ2EY3bvzojdlHqnWZClpM5ddRtf1OBeEzLRw5OFlHDRs7fIZABFWICGicbeikW8n630BSZCsGcXRq6ho6DIrXVnqXvZBRdqhtlfNw8mtNotZA4IrkR2ZBZBijAJjPuqtkb0f9Mwe7JELI5ORDZBvAbPTL9MZAFWglqtxvmQ1tNnEODPDXgvvbKpKv31A5TSRZAR50qxQj9em9f2X3wPK"
  phone_id: "1077709502094473"
  codigo_pais: "57"

scheduler:
  dias_vencimiento: 30
